version: '3.5'

services:
  reverse-proxy:
    image: traefik:v2.10
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "80:80"
      - "443:443"
    volumes:
      - "./traefik.yaml:/etc/traefik/traefik.yaml"
      - "./data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/log/traefik:/var/log"  # For access log
