entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
  websecure:
    address: ":443"

api:
  dashboard: true
  insecure: true

providers:
  docker: {}

accessLog: {}

certificatesResolvers:
  staging:
    acme:
      email: ${EMAIL}
      storage: /data/letsencrypt_staging.json
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      httpChallenge:
        entryPoint: web

  production:
    acme:
      email: ${EMAIL}
      storage: /data/letsencrypt_prod.json
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      httpChallenge:
        entryPoint: web
